import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AudioPlayingProvider } from "../provider/AudioPlayingProvider";
import { CurrentAudioIdProvider } from "../provider/CurrentAudioIdProvider";
import { AudioCurrentTimeProvider } from "../provider/AudioCurrentTimeProvider";
import { AudioPlayerModal } from "@/component/AudioPlayerModal";
import { AudioPlayerModalProvider } from "@/provider/AudioPlayerModalProvider";
import { AudioProvider } from "@/provider/AudioProvider";
import { fetchSongs } from "@/lib/fetchSongs";
import { SongsProvider } from "@/provider/SongsProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const songs = await fetchSongs();

  console.log("##########$$$$d");
  console.log(songs);

  return (
    <html lang="ja">
      <body className={inter.className}>
        <AudioPlayingProvider>
          <CurrentAudioIdProvider>
            <AudioCurrentTimeProvider>
              <AudioPlayerModalProvider>
                <SongsProvider songs={songs}>
                  <AudioProvider>
                    <div className="font-sans text-white">{children}</div>
                    <AudioPlayerModal />
                  </AudioProvider>
                </SongsProvider>
              </AudioPlayerModalProvider>
            </AudioCurrentTimeProvider>
          </CurrentAudioIdProvider>
        </AudioPlayingProvider>
      </body>
    </html>
  );
}
